import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import cn from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "max-w-7xl mx-auto")}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow flex-1 py-8 px-4">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
